version: '3'

services:
  mongo:
    # since mongo is an offical image we can use it.
    image: "mongo"

    # the port that we want to publish for mongodb
    ports:
      - "27017:27017"
    networks:
      - exam-app

    # our mongodb depends on volume to keep the data alive.
    volumes:
      - mongo-data:/data/db


  nginx:
    depends_on:
      - api
      - client
    restart: always
    networks:
      - exam-app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mongo
    networks:
      - exam-app  
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    networks:
      - exam-app
    volumes:
      - /app/node_modules
      - ./client:/app
networks:
  exam-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local